"""Builds supabase/seed.sql: schools and the email domains that map to them.

A school's domain is its INSTURL host. Web-only prefixes (web., wp., ...) are stripped. When
several campuses share one domain it goes to the largest campus, and hand-reviewed extras in
crosswalks/school_domains_extra.csv override the rest (e.g. @umn.edu -> Twin Cities).
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

WEB_PREFIXES = ("web.", "wp.", "wwwcp.", "new.", "www2.", "home.")


def email_domain(site: str) -> str:
    for p in WEB_PREFIXES:
        if site.startswith(p) and site.count(".") >= 2:
            return site[len(p) :]
    return site


def domain_map(schools: list[dict], extras: list[dict]) -> dict[str, int]:
    by_domain: dict[str, list[dict]] = {}
    for s in schools:
        if s.get("domain"):
            by_domain.setdefault(email_domain(s["domain"]), []).append(s)
    out = {d: max(group, key=lambda s: (s["ugSize"], -s["id"]))["id"] for d, group in by_domain.items()}
    ids = {s["id"] for s in schools}
    for e in extras:
        unitid = int(e["unitid"])
        if unitid not in ids:
            raise ValueError(f"school_domains_extra: {e['domain']} points at unknown unitid {unitid}")
        out[e["domain"].lower()] = unitid
    return dict(sorted(out.items()))


def _q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def seed_sql(snapshot: Path, extras_csv: Path) -> str:
    doc = json.loads(snapshot.read_text())
    schools = doc["schools"]
    with extras_csv.open(newline="") as fh:
        extras = list(csv.DictReader(fh))
    domains = domain_map(schools, extras)
    lines = [
        f"-- Generated by `college-etl seed-sql` from snapshot {doc['snapshotId']}. Do not edit by hand.",
        "insert into public.schools (id, name, state) values",
        ",\n".join(f"  ({s['id']}, {_q(s['name'])}, {_q(s['state'])})" for s in schools) + ";",
        "",
        "insert into public.school_domains (domain, school_id) values",
        ",\n".join(f"  ({_q(d)}, {sid})" for d, sid in domains.items()) + ";",
        "",
    ]
    return "\n".join(lines)
