import type { MetricDef, MetricGroup, MetricKey } from './types';
import { METRIC_KEYS } from './types';

const defs: Record<MetricKey, Omit<MetricDef, 'key'>> = {
  grad_rate: {
    label: 'Graduation rate',
    short: 'Grad rate',
    group: 'outcomes',
    direction: 'higher',
    unit: 'percent',
    description: 'Share of first-time, full-time students who finish within 6 years (150% time).',
  },
  retention_rate: {
    label: 'First-year retention',
    short: 'Retention',
    group: 'outcomes',
    direction: 'higher',
    unit: 'percent',
    description: 'Share of first-time, full-time students who return for a second year.',
  },
  median_earnings_10y: {
    label: 'Median earnings, 10 years out',
    short: 'Earnings',
    group: 'outcomes',
    direction: 'higher',
    unit: 'usd',
    description: 'Median earnings of federally aided students 10 years after entry.',
  },
  pell_grad_rate: {
    label: 'Pell recipient graduation rate',
    short: 'Pell grad rate',
    group: 'outcomes',
    direction: 'higher',
    unit: 'percent',
    description: '6-year completion rate for students who received a Pell grant.',
  },
  net_price: {
    label: 'Average net price',
    short: 'Net price',
    group: 'cost',
    direction: 'lower',
    unit: 'usd',
    description: 'Average annual cost after grants and scholarships, for aided students.',
  },
  net_price_low_income: {
    label: 'Net price, family income under $30K',
    short: 'Low-income price',
    group: 'cost',
    direction: 'lower',
    unit: 'usd',
    description: 'Average annual net price for aided students from families earning $0-30,000.',
  },
  median_debt: {
    label: 'Median debt at graduation',
    short: 'Debt',
    group: 'cost',
    direction: 'lower',
    unit: 'usd',
    description: 'Median federal loan debt of students who completed.',
  },
  earnings_to_price: {
    label: 'Earnings to price',
    short: 'Value',
    group: 'cost',
    direction: 'higher',
    unit: 'ratio',
    description: 'Median 10-year earnings divided by four years of net price.',
  },
  faculty_count: {
    label: 'Full-time instructional staff',
    short: 'Faculty',
    group: 'teaching',
    direction: 'higher',
    unit: 'count',
    description: 'Number of full-time instructional staff (IPEDS, via Urban Institute).',
  },
  student_faculty_ratio: {
    label: 'Student-to-faculty ratio',
    short: 'Class ratio',
    group: 'teaching',
    direction: 'lower',
    unit: 'ratio',
    description: 'Students per instructional faculty member.',
  },
  ft_faculty_share: {
    label: 'Share of faculty who are full-time',
    short: 'Full-time faculty',
    group: 'teaching',
    direction: 'higher',
    unit: 'percent',
    description: 'Full-time faculty as a share of all instructional faculty.',
  },
  instructional_spend_per_fte: {
    label: 'Instructional spending per student',
    short: 'Teaching spend',
    group: 'teaching',
    direction: 'higher',
    unit: 'usd',
    description: 'Instructional expenditures per full-time-equivalent student.',
  },
  faculty_salary: {
    label: 'Average faculty salary',
    short: 'Faculty pay',
    group: 'teaching',
    direction: 'higher',
    unit: 'usd',
    description: 'Average salary of full-time instructional faculty (Scorecard reports it monthly; shown per year).',
  },
  research_total: {
    label: 'Total R&D spending',
    short: 'Research',
    group: 'research',
    direction: 'higher',
    unit: 'usd',
    description: 'Total research and development expenditures (NSF HERD FY2024).',
  },
  research_per_student: {
    label: 'R&D spending per student',
    short: 'Research/student',
    group: 'research',
    direction: 'higher',
    unit: 'usd',
    description: 'Total R&D divided by undergraduate plus graduate enrollment.',
  },
  clubs_count: {
    label: 'Student organizations',
    short: 'Clubs',
    group: 'campus',
    direction: 'higher',
    unit: 'count',
    description: 'Registered student organizations listed on the campus directory.',
  },
  clubs_per_1k_ug: {
    label: 'Clubs per 1,000 undergrads',
    short: 'Clubs/1k',
    group: 'campus',
    direction: 'higher',
    unit: 'ratio',
    description: 'Student organizations per 1,000 undergraduate students.',
  },
  admit_rate: {
    label: 'Admission rate',
    short: 'Admit rate',
    group: 'preference',
    direction: 'preference',
    defaultDirection: 'lower',
    unit: 'percent',
    description: 'Share of applicants admitted. Choose whether you want more or less selective.',
  },
  sat_avg: {
    label: 'Average SAT',
    short: 'SAT',
    group: 'preference',
    direction: 'preference',
    defaultDirection: 'higher',
    unit: 'score',
    description: 'Average SAT equivalent score of admitted students.',
  },
  undergrad_size: {
    label: 'Undergraduate enrollment',
    short: 'Size',
    group: 'preference',
    direction: 'preference',
    defaultDirection: 'lower',
    unit: 'count',
    description: 'Degree-seeking undergraduates. Choose whether you want bigger or smaller.',
  },
  endowment_per_student: {
    label: 'Endowment per student',
    short: 'Endowment',
    group: 'resources',
    direction: 'higher',
    unit: 'usd',
    description: 'End-of-year endowment divided by total enrollment.',
  },
  crowd_overall: {
    label: 'Student rating: overall',
    short: 'Overall',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_academics: {
    label: 'Student rating: academics',
    short: 'Academics',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_social: {
    label: 'Student rating: social life',
    short: 'Social',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_career: {
    label: 'Student rating: career support',
    short: 'Career',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_housing: {
    label: 'Student rating: housing',
    short: 'Housing',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_safety: {
    label: 'Student rating: safety',
    short: 'Safety',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
  crowd_value: {
    label: 'Student rating: value',
    short: 'Value rating',
    group: 'crowd',
    direction: 'higher',
    unit: 'rating',
    description: 'Bayesian-averaged rating from verified students (1-5).',
  },
};

/** Fixed registry order. Scores are always summed in this order so results are bit-for-bit stable. */
export const METRICS: readonly MetricDef[] = METRIC_KEYS.map((key) => ({ key, ...defs[key] }));

export const METRIC_BY_KEY: Readonly<Record<MetricKey, MetricDef>> = Object.fromEntries(
  METRICS.map((m) => [m.key, m]),
) as Record<MetricKey, MetricDef>;

export const GROUPS: readonly { key: MetricGroup; label: string }[] = [
  { key: 'outcomes', label: 'Outcomes' },
  { key: 'cost', label: 'Cost and value' },
  { key: 'teaching', label: 'Teaching' },
  { key: 'research', label: 'Research' },
  { key: 'campus', label: 'Campus life' },
  { key: 'resources', label: 'Resources' },
  { key: 'preference', label: 'Your preferences' },
  { key: 'crowd', label: 'Student reviews' },
];

export const CROWD_KEYS = METRICS.filter((m) => m.group === 'crowd').map((m) => m.key);

export function isMetricKey(value: string): value is MetricKey {
  return value in defs;
}
